#!/usr/bin/env python3
"""Text-safe pairing table: generate and verify.

The pairing table in docs/colors.html ("Which text is safe on which
surface") is GENERATED from the two stylesheets by this script and
embedded between marker comments. Run with --emit to print the current
fragment; run with no arguments to verify that the embedded table still
matches the stylesheets. A mismatch means a token changed after the
table was last regenerated — regenerate, do not hand-edit.

Why this exists: three shipped bugs (the watermark, the skip link, the
nav group labels) were text elements borrowing tokens from non-text
roles. The table is the positive statement of which pairings are safe,
and this check keeps it true when tokens change.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUB = ROOT / "docs/design-system.css"
INT = ROOT / "docs/internal/internal-tools.css"
COLORS = ROOT / "docs/colors.html"
BEGIN, END = "<!-- contrast-table:begin (generated by verification/check-contrast.py) -->", "<!-- contrast-table:end -->"

def parse_block(text, start_marker):
    i = text.index(start_marker)
    j = text.index("{", i)
    depth, k = 1, j + 1
    while depth and k < len(text):
        depth += text[k] == "{"
        depth -= text[k] == "}"
        k += 1
    # Capture hex values AND var() references — since the primitive layer
    # landed, a semantic token usually points at a primitive rather than
    # carrying a hex of its own. resolve() flattens the chain.
    return dict(re.findall(r"(--[a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{3,6}|var\(--[a-z0-9-]+\))", text[j:k]))

def resolve(d):
    """Flatten var(--x) chains to the hex they end at."""
    out = dict(d)
    for _ in range(8):
        changed = False
        for key, val in list(out.items()):
            m = re.fullmatch(r"var\((--[a-z0-9-]+)\)", val.strip())
            if m and m.group(1) in out and out[m.group(1)] != val:
                out[key] = out[m.group(1)]; changed = True
        if not changed: break
    return {k: v for k, v in out.items() if v.startswith("#")}

def tokens(css_path, dark_marker):
    s = css_path.read_text()
    raw_light = parse_block(s, ":root {")
    raw_dark = dict(raw_light)
    raw_dark.update(parse_block(s, dark_marker))
    # Resolve within each mode: a dark semantic token may point at a
    # primitive declared in :root, so the light map seeds the dark one.
    return resolve(raw_light), resolve(raw_dark)

def lum(hexv):
    h = hexv.lstrip("#")
    if len(h) == 3: h = "".join(c*2 for c in h)
    r, g, b = (int(h[i:i+2], 16)/255 for i in (0, 2, 4))
    f = lambda v: v/12.92 if v <= 0.03928 else ((v+0.055)/1.055)**2.4
    r, g, b = f(r), f(g), f(b)
    return 0.2126*r + 0.7152*g + 0.0722*b

def ratio(fg, bg):
    l1, l2 = lum(fg), lum(bg)
    hi, lo = max(l1, l2), min(l1, l2)
    return round((hi + 0.05) / (lo + 0.05), 2)

# ── Curated pairing spec.  prefix, text rows, surface columns ──────────
# Both surfaces now share one token vocabulary, so the row and column names are
# the same for each; only the values behind them differ.
PUBLIC_TEXT = ["text", "text-muted", "link", "link-hover", "link-visited"]
PUBLIC_SURF = ["canvas", "surface", "surface-muted", "accent-surface", "accent-wash"]
PUBLIC_SPECIAL = [("text-on-accent", "accent"), ("text-on-accent", "accent-hover")]
PUBLIC_STATUS = [("info-fg", "info-bg"), ("success-fg", "success-bg"), ("warning-fg", "warning-bg"), ("error-fg", "error-bg")]
PUBLIC_NEVER = [("border-strong", "interactive borders, tracks, and arrows (3:1 non-text minimum)"),
                ("text-disabled", "disabled text only — exempt from AA, never for content"),
                ("border", "decorative hairlines"), ("border-muted", "component borders")]

INT_TEXT = ["text", "text-muted", "link", "link-hover", "link-visited"]
INT_SURF = ["canvas", "surface", "surface-muted", "surface-hover", "surface-hover-strong"]
INT_SPECIAL = [("text-on-accent", "accent"), ("text-on-accent", "accent-hover"), ("text-on-accent", "accent-active")]
INT_STATUS = [("info-fg", "info-bg"), ("success-fg", "success-bg"), ("warning-fg", "warning-bg"), ("error-fg", "error-bg")]
INT_NEVER = [("border-strong", "borders and arrows (3:1 non-text minimum)"),
             ("text-disabled", "disabled text only"), ("accent-disabled-fg", "disabled accent buttons only"),
             ("disabled-fg", "disabled secondary buttons only"), ("danger-disabled-fg", "disabled danger buttons only")]

def cell(fg_l, bg_l, fg_d, bg_d, var_fg, var_bg):
    rl, rd = ratio(fg_l, bg_l), ratio(fg_d, bg_d)
    ok_l, ok_d = rl >= 4.5, rd >= 4.5
    if ok_l and ok_d:
        return ('<td class="ct-ok" style="background:var({bg});color:var({fg})">Aa <span class="ct-r">{rl} / {rd}</span></td>'
                .format(bg=var_bg, fg=var_fg, rl=rl, rd=rd))
    marks = "{}{} / {}{}".format(rl, "" if ok_l else "✗", rd, "" if ok_d else "✗")
    return '<td class="ct-no"><span class="ct-r">{}</span></td>'.format(marks)

def matrix(prefix, light, dark, text_rows, surf_cols, special, status):
    p = lambda n: prefix + n
    out = []
    out.append('<table class="ct-table"><thead><tr><th scope="col">text \\ surface</th>')
    for sc in surf_cols:
        out.append('<th scope="col"><code>{}</code></th>'.format(p(sc)))
    out.append("</tr></thead><tbody>")
    for tr_ in text_rows:
        out.append('<tr><th scope="row"><code>{}</code></th>'.format(p(tr_)))
        for sc in surf_cols:
            out.append(cell(light[p(tr_)], light[p(sc)], dark[p(tr_)], dark[p(sc)], p(tr_), p(sc)))
        out.append("</tr>")
    for fg, bg in special + status:
        out.append('<tr><th scope="row"><code>{}</code> on <code>{}</code></th>'.format(p(fg), p(bg)))
        out.append('<td colspan="{}">'.format(len(surf_cols)).replace('<td ', '<td class="ct-span" '))
        out.append(cell(light[p(fg)], light[p(bg)], dark[p(fg)], dark[p(bg)], p(fg), p(bg)).replace("<td ", "<span ").replace("</td>", "</span>"))
        out.append("</td></tr>")
    out.append("</tbody></table>")
    return "".join(out)

def never_list(prefix, items):
    p = lambda n: prefix + n
    lis = "".join("<li><code>{}</code> — {}</li>".format(p(n), role) for n, role in items)
    return '<ul class="ct-never">' + lis + "</ul>"

def emit():
    pub_l, pub_d = tokens(PUB, '[data-theme="dark"] {')
    # The staff sheet is tier 2: it declares only what differs, and a staff page
    # loads tier 1 first. So the palette a staff page actually sees is tier 1
    # with tier 2 layered over it — which is what has to be measured.
    ovr_l, ovr_d = tokens(INT, "@media (prefers-color-scheme: dark)")
    int_l, int_d = dict(pub_l), dict(pub_d)
    int_l.update(ovr_l); int_d.update(ovr_d)
    frag = []
    frag.append(BEGIN)
    frag.append('<p class="ct-note">Each passing cell renders its own pairing in your current mode; the numbers are the '
                'measured contrast in <em>light / dark</em>. ✗ marks a ratio below WCAG AA for normal text (4.5:1). '
                'Large text (24px, or 18.66px bold) only needs 3:1, so a ✗ cell may still be usable for headings '
                '— check the number.</p>')
    frag.append("<h3>Public palette</h3>")
    frag.append(matrix("--ds-", pub_l, pub_d, PUBLIC_TEXT, PUBLIC_SURF, PUBLIC_SPECIAL, PUBLIC_STATUS))
    frag.append('<p class="ct-note">The dark chrome bars (<code>--ds-chrome</code>) are dark in both modes: text on '
                'them must be pinned to light values, never taken from flipping tokens — see the site header construction.</p>')
    frag.append("<h4>Looks tempting, is not for reading text</h4>")
    frag.append(never_list("--ds-", PUBLIC_NEVER))
    frag.append("<h3>Internal palette</h3>")
    frag.append(matrix("--ds-", int_l, int_d, INT_TEXT, INT_SURF, INT_SPECIAL, INT_STATUS))
    frag.append("<h4>Looks tempting, is not for reading text</h4>")
    frag.append(never_list("--ds-", INT_NEVER))
    frag.append(END)
    return "\n".join(frag)

def main():
    frag = emit()
    if "--emit" in sys.argv:
        print(frag); return 0
    s = COLORS.read_text()
    if BEGIN not in s:
        print("FAIL  colors.html has no generated contrast table (markers missing)"); return 1
    current = s[s.index(BEGIN): s.index(END) + len(END)]
    if current.strip() == frag.strip():
        print("PASS  text-safe pairing table matches the stylesheets"); return 0
    print("FAIL  pairing table drifted from stylesheet tokens — regenerate:")
    print("      python3 verification/check-contrast.py --emit  (paste between the markers)")
    return 1

if __name__ == "__main__":
    sys.exit(main())
